### ISSUE TITLE
Identity lines contain errant spaces

### ISSUE THREAD

**Issue by adamroach** [fluffy/ietf#16]
There are 2 instances of `a=identity` lines that contain spaces in the identity value but which are otherwise valid. While it's going to look untidy in the XML source, the only solution here is to place the entire identity on the same line in the source file.

**Comment by suhasHere** [comment]
@adamroach  I tried fixing the identity line by removing the space and it destroys the readability.
 However, the current draft has the following text on the formatting.

The SDP examples deviate from actual on-the-wire SDP notation in several ways. This is done to facilitate readability and to conform to the restrictions imposed by the RFC formatting rules.
1. Visual markers/Empty lines in any SDP example are inserted to make functional divisions in the SDP clearer, and are not actually part of the SDP syntax.
2. Any SDP line that is indented (compared to the initial line in the SDP block) is a continuation of the preceding line. The line break and indent are to be interpreted as a single space character.
3. Excepting the above two conventions, line endings are to be interpreted as <CR><LF> pairs (that is, an ASCII 13 followed by an ASCII 10).

How about extending the point 2  above with something like this
Any SDP line that is indented (compared to the initial line in the SDP block) is a continuation of the preceding line. The line break and indent are to be interpreted as a single space character. The SDP attributes "a=identity" is affected by this formatting

**Comment by suhasHere** [comment]
@adamroach  please check #21
