### ISSUE TITLE
Fingerprint value in 5.4.5 SDP Answer has multiple issues

### ISSUE THREAD

**Issue by adamroach** [fluffy/ietf#18]
The fingerprint attribute in example `5.4.5 SDP Answer` has invalid additional colons (including a trailing colon), additional spaces, and some "octets" that are three hex digits long:

```
a=fingerprint:sha-256 BB:0A9:0E:05:E9:26:33:E8:70:88:A25:2F:70:9F:04: :19:E2:1C:3B:4B:9F:81:5:2F:70:9F:04::F4:A5:A8:D8:
```

**Comment by suhasHere** [comment]
Resolved in #22
