### ISSUE TITLE
BUNDLE alignment

### ISSUE THREAD

**Issue by cdh4u** [fluffy/ietf#19]
The examples also need to be updated in order to reflect the latest version of BUNDLE: apart from the initial offer (read: before the bundle group has been created), the port is ONLY assigned to the bundled m- section represented by the BUNDLE-tag. All other m- sections (both in offers and answers) have a zero port value and an SDP bundle-only attribute.

**Comment by suhasHere** [comment]
@cdh4u Started the work in #26
