### ISSUE TITLE
SDP Examples document contains errant double-spaces

### ISSUE THREAD

**Issue by adamroach** [fluffy/ietf#9]
There are 50 instances of candidate lines being unparsable due to the presence of multiple space characters where only a single space is allowed per syntax.

**Comment by suhasHere** [comment]
@adamroach The spaces were added to aid in readability given that we have tabular representation.

**Comment by adamroach** [comment]
Given that some people have expressed an interest in validating these examples programmatically, I think having them correct is pretty important. If you do feel the need to insert extra spaces, please include a note to that effect and ensure that they do only fall in locations that improve readability.

**Comment by suhasHere** [comment]
@adamroach  sorry for the confusion. my comment was more on having a=identity on multiple lines. I will fix the a=candidate formatting.

**Comment by suhasHere** [comment]
fixed and pushed in the master !!
